version: '3'

services:
  api:
    build: .
    container_name: test
    entrypoint: ""
    command: "python /test/test.py"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/test
  db:
    image: mysql:5.7
    container_name: test_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
